/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminBooksRouteImport } from './routes/admin/books'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as publicBooksRouteImport } from './routes/(public)/books'
import { Route as publicLayoutRouteImport } from './routes/(public)/_layout'
import { Route as publicBooksSlugRouteImport } from './routes/(public)/books.$slug'

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBooksRoute = publicBooksRouteImport.update({
  id: '/(public)/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBooksSlugRoute = publicBooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => publicBooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/books': typeof publicBooksRouteWithChildren
  '/admin': typeof AdminLayoutRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/books/$slug': typeof publicBooksSlugRoute
}
export interface FileRoutesByTo {
  '/books': typeof publicBooksRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/': typeof publicIndexRoute
  '/books/$slug': typeof publicBooksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/_layout': typeof publicLayoutRoute
  '/(public)/books': typeof publicBooksRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/(public)/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(public)/books/$slug': typeof publicBooksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/books'
    | '/admin'
    | '/admin/books'
    | '/admin/login'
    | '/admin/orders'
    | '/'
    | '/admin/'
    | '/books/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/books'
    | '/admin'
    | '/admin/books'
    | '/admin/login'
    | '/admin/orders'
    | '/'
    | '/books/$slug'
  id:
    | '__root__'
    | '/(public)/_layout'
    | '/(public)/books'
    | '/admin/_layout'
    | '/admin/books'
    | '/admin/login'
    | '/admin/orders'
    | '/(public)/'
    | '/admin/'
    | '/(public)/books/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRoute
  publicBooksRoute: typeof publicBooksRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  publicIndexRoute: typeof publicIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/books': {
      id: '/(public)/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof publicBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_layout': {
      id: '/(public)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/books/$slug': {
      id: '/(public)/books/$slug'
      path: '/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof publicBooksSlugRouteImport
      parentRoute: typeof publicBooksRoute
    }
  }
}

interface publicBooksRouteChildren {
  publicBooksSlugRoute: typeof publicBooksSlugRoute
}

const publicBooksRouteChildren: publicBooksRouteChildren = {
  publicBooksSlugRoute: publicBooksSlugRoute,
}

const publicBooksRouteWithChildren = publicBooksRoute._addFileChildren(
  publicBooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRoute,
  publicBooksRoute: publicBooksRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  publicIndexRoute: publicIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
